WIP: Decouple CSS used for dynamic components in React layer
GitNation/react-app-layer pull request #2
Opened 2020-09-19 17:39 UTC by Severenit

Decouple CSS used for dynamic components in React layer

2020-09-21 10:41 UTC, operatino commented on src/dialogs/styled.js
> +     --color-speaker-info
rename to popup-track-info

2020-09-21 10:42 UTC, operatino commented on src/dialogs/styled.js
> +  background: var(--color-speaker-info);
add fallback colors

2020-09-21 10:43 UTC, operatino commented on src/dialogs/styled.js
> + * In this document we used css variable:
make sure all variables have fallback values

2020-09-21 10:44 UTC, operatino commented on src/dialogs/styled.js
> +     --background-head-image
use base64 encoded image in react-app-layer as default

2020-09-21 12:12 UTC, Severenit reviewed
I did all the tasks, that we have discussed.

2020-09-22 10:11 UTC, UsulPro requested changes
Looks good in general. Please find my comments below

2020-09-22 10:11 UTC, UsulPro commented on src/dialogs/styled.js
> +`;
Can we please divide this file to per component styles (like `SpeckerCard.styled.js`, `DialogPopup.styled.js` and so on) keeping here only common reusable styles? So it will be easier for us to extend components in the future

2020-09-22 10:13 UTC, UsulPro commented on src/dialogs/SpeakerCard.js
> +
```suggestion
```

2020-09-25 00:05 UTC, Severenit reviewed
I've done)

2020-09-25 18:44 UTC, operatino commented
@Severenit I see that `time-track` component styles are not moved yet... let's keep this PR to popup only, but the Trello task will need more work

2020-09-25 19:03 UTC, UsulPro commented
My comments are marked as resolved but still not fixed or answered

>only these two are defined in a conference project. Where others are coming from?

>`border: 15px solid var(--color-popup-border, #5f5f5f);` can we add fallbacks to variables itself?

2020-09-27 14:39 UTC, operatino commented
@Severenit @UsulPro I've merged this PR manually with few fixes applied, but we still need to continue work on this Trello task and finish time track styles transfer + fix Oleg's review comments.

2020-09-27 14:39 UTC, closed without merging